### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by sixcorners** [sixcorners-docker/cloudflare-warp#6]

**Comment by ddhhz** [comment]
Thanks for the image!

1. Fetch `cloudflare_warp.pem` from https://www.cloudflare.com/a/warp 
2. hello-world example
```
version: "3"
services:
  warp:
    container_name: warp
    image: sixcorners/cloudflare-warp
    volumes:
     - ./cloudflare-warp.pem:/run/secrets/cloudflare-warp.pem:ro
    command: cloudflare-warp --hostname warp.example.com --hello-world
```
3. another example
```
version: "3"
services:
  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: always
    expose:
     - 80
    networks:
     - front
  warp:
    container_name: warp
    image: sixcorners/cloudflare-warp
    restart: always
    volumes:
     - ./cloudflare-warp.pem:/run/secrets/cloudflare-warp.pem:ro
    networks:
     - front
    command: cloudflare-warp --hostname warp.example.com http://webserver:80

networks:
  front: 
```
